pipes
kikke88/TechSphereCplusplus pull request #1
Opened 2020-10-09 12:00 UTC by kikke88

2020-10-10 13:04 UTC, a-badin requested changes

2020-10-10 13:04 UTC, a-badin commented on main_program/lib/pipeline/src/pipeline.cpp
> +			already_read += read(static_cast<char*>(data) + already_read, len - already_read);
read может вернуть 0, тогда будет цикл

2020-10-10 13:04 UTC, a-badin commented on main_program/lib/pipeline/include/pipeline.hpp
> +		bool call_close_from_destructor_ = false;
Не нужен

2020-10-14 13:51 UTC, kikke88 commented on main_program/lib/pipeline/include/descriptor.hpp
> +		bool is_close() const;
не могу я себя заставить использовать static_cast<bool> вместо метода, который ясно даёт понять, что он проверяет

2020-10-15 15:08 UTC, a-badin approved these changes
Уберите check_error из класса и поменяйте тип исключения на где read вернул 0, или просто возвращайте 0. Когда сделайте сливайте в мастер

2020-10-15 15:08 UTC, a-badin commented on main_program/lib/pipeline/include/descriptor.hpp
> +		bool is_close() const;
да, это может быть некрасиво, но конкретно у explicit operator bool() есть особенность - он без кастов конвертится в if, for и в while

2020-10-15 15:08 UTC, a-badin commented on main_program/lib/pipeline/include/pipeline.hpp
> +		void check_error(ssize_t err, const std::string& func_name);
А тут она зачем осталась

2020-10-15 15:08 UTC, a-badin commented on main_program/lib/pipeline/src/pipeline.cpp
> +			throw std::runtime_error("Read error: pipe was closed by writter");
на самом деле тут вполне допустимо было возвращать 0. Просто потому что ловить 0 мы будет довольно часто - ситуация на грани исключительности. И уж точно если оставлять исключение, нужно завести отдельное.  Потому что сейчас мы не можем различать ситуации, когда у нас ошибка чтения и когда у нас закрылся пайп - и там и там std::runtime_error

2020-10-15 15:08 UTC, a-badin commented on main_program/src/main.cpp
> +	len = pipe2.read(buf, 512);
вот, например, тут вы не знаете сколько данных вернет date. А вдруг больше чем 512, а вдруг он вренул 10 но это еще не все? Этот вызов тут нужно в цикле вызывать как раз до тех пор пока read не вернет 0 или в вашем случае, пока он не кинет какое-нибудь специальное исключение по которому можно понять, что вывод date закончился

2020-10-15 15:09 UTC, merged