log lib
kikke88/TechSphereCplusplus pull request #2
Opened 2020-10-16 09:10 UTC by kikke88

2020-10-20 10:32 UTC, kikke88 commented
Исправлено

- переменные в enum class большими буквами
- добавил explicit конструктору Base Logger
- переделал логику вызова функции log
- level_ теперь protected
- исправил опечатку (init_with_stderr_logger(str,log_levev) -> init_with_file_logger(str,log_levev))
- удалил конструктор перемещения и перемещающего присваивания для синглтона

2020-10-20 15:32 UTC, Kapitonov requested changes

2020-10-20 15:32 UTC, Kapitonov commented on main_program/lib/log/include/base_logger.hpp
> +	private:
Давайте сбда перенесем все потоки как std::ostream, тогда функцию log можно перенести в BaseLogger и не дублировать его код. Также можно будет обобзить метод flush.

2020-10-20 15:46 UTC, kikke88 commented on main_program/lib/log/include/base_logger.hpp
> +	private:
Простите, пожалуйста, я случайно нажал на ререквест, думал, что вы ещё прошлые изменения не просмотрели.

2020-10-25 10:59 UTC, Kapitonov requested changes

2020-10-25 10:59 UTC, Kapitonov commented on main_program/lib/log/include/file_logger.hpp
> +		std::ofstream file_stream;
Переменные обычно имеют префикс или постфикс.

2020-10-25 10:59 UTC, Kapitonov commented on main_program/lib/log/src/singletone.cpp
> +	Singleton& singleton = Singleton::get_instance();
Лучше так не делать, а делать вызов функции внутри.

2020-10-25 10:59 UTC, Kapitonov commented on main_program/lib/log/src/singletone.cpp
> +		return *base_ptr_;
Что вернет ваша функция, до вызова set_global_logger? Предлагаю поставить какое-нибудь дефолное значение логгера, например Stderror_logger.

2020-10-30 07:51 UTC, Kapitonov requested changes

2020-10-30 07:51 UTC, Kapitonov commented on main_program/lib/log/src/base_logger.cpp
> +		flush();
Что произойдет, если это будет классFileLogger, в деструкторе FileLogger удалится сам файл и выховете flush у ссылки непонятно куда?

2020-10-30 07:51 UTC, Kapitonov commented on main_program/lib/log/include/singleton.hpp
> +	void init_with_stderr_logger(Log_Level);
А где функция установки уровня логгирования?

2020-11-03 15:41 UTC, Kapitonov requested changes

2020-11-03 15:41 UTC, Kapitonov commented on main_program/lib/log/src/singletone.cpp
> +			instance.set_global_logger(std::make_unique<Stderr_Logger>(Log_Level::DEBUG));
Давайте перенесем в конструктор. Тогда метод станет компактным и более правильным.

2020-11-12 01:07 UTC, Kapitonov commented
Поправьте конфликты и сливайте.

2020-11-12 06:39 UTC, merged

2020-11-12 19:11 UTC, Kapitonov requested changes
Поправьте и сливайте.

2020-11-12 19:11 UTC, Kapitonov commented on main_program/lib/log/src/stderr_logger.cpp
> +		flush();
Не имеет смысла, поскольку для stderr выполняется после каждой записи.

2020-11-12 19:11 UTC, Kapitonov commented on main_program/lib/log/src/file_logger.cpp
> +		flush();
Деcтруктор std::ofstream сам это сделает.